# SPDX-License-Identifier: GPL-3.0-or-later
# Based on Calligraphy by GeopJr <https://codeberg.org/GeopJr/Calligraphy>
# Originally by Gregor "gregorni" Niehl
from __future__ import annotations

import base64

_ATTRIBUTION = (
    "Based on Calligraphy by GeopJr <https://codeberg.org/GeopJr/Calligraphy>\n"
    '# Originally by Gregor "gregorni" Niehl — Licensed under GPL v3'
)


def write_stdout(lines: list[str]) -> None:
    """Print lines to stdout joined by newlines."""
    print("\n".join(lines))


def write_ansi_file(lines: list[str], path: str, version: str) -> None:
    """Write ANSI-escaped lines to a file with an attribution header.

    The resulting file can be replayed with: cat <path>
    Raises OSError on write failure.
    """
    header = (
        f"# Generated by color-banner {version}\n"
        f"# {_ATTRIBUTION}\n"
        f"# cat this file to display the banner\n"
    )
    content = header + "\n".join(lines) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def write_shell_export(
    lines: list[str],
    path: str,
    version: str,
    function_name: str = "show_banner",
) -> None:
    """Write a self-contained bash function that replays the banner.

    The ANSI output is base64-encoded and embedded inline.
    Raises OSError on write failure.
    """
    ansi_bytes = ("\n".join(lines) + "\n").encode("utf-8")
    b64 = base64.b64encode(ansi_bytes).decode("ascii")
    script = (
        f"#!/usr/bin/env bash\n"
        f"# Generated by color-banner {version}\n"
        f"# {_ATTRIBUTION}\n"
        f"# Paste this function into your script or .bashrc\n"
        f"{function_name}() {{\n"
        f"  printf '%s' \"$(printf '%s' '{b64}' | base64 -d)\"\n"
        f"}}\n"
        f"{function_name}\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(script)
