# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import base64
import re
from html import escape as _html_escape
from pathlib import Path

_VALID_FUNCTION_NAME = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")

_ATTRIBUTION_LINE1 = "Inspired by Calligraphy by GeopJr <https://codeberg.org/GeopJr/Calligraphy>"
_ATTRIBUTION_LINE2 = 'Originally by Gregor "gregorni" Niehl — Licensed under Apache 2.0'


def write_stdout(lines: list[str]) -> None:
    """Print lines to stdout joined by newlines."""
    print("\n".join(lines))


def _build_ansi_header(version: str, extra: str = "") -> str:
    """Build the standard ANSI file header with an optional extra comment line.

    Args:
        version: color-banner version string.
        extra: Optional extra comment line (e.g. ``"# Font: slant (#001)\\n"``).
               Must include a trailing newline if provided.
    """
    base = (
        f"# Generated by color-banner {version}\n"
        f"# {_ATTRIBUTION_LINE1}\n"
        f"# {_ATTRIBUTION_LINE2}\n"
    )
    if extra:
        base += extra
    return base + "# cat this file to display the banner\n"


def write_ansi_file(lines: list[str], path: str, version: str) -> None:
    """Write ANSI-escaped lines to a file with an attribution header.

    Parent directories are created automatically.
    The resulting file can be replayed with: cat <path>
    Raises OSError on write failure.
    """
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    content = _build_ansi_header(version) + "\n".join(lines) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def write_ansi_files_all(
    font_banners: list[tuple[int, str, list[str]]],
    dir_path: str,
    version: str,
) -> None:
    """Write one ANSI file per font into dir_path.

    Each file is named NNN-fontname.ans where NNN is the zero-padded
    1-based font number.  dir_path is created automatically if needed.

    Args:
        font_banners: list of (number, font_name, lines) tuples.
        dir_path: output directory path (created if it does not exist).
        version: color-banner version string for the file header.
    """
    out = Path(dir_path)
    out.mkdir(parents=True, exist_ok=True)
    for num, font_name, lines in font_banners:
        filename = f"{num:03d}-{font_name}.ans"
        file_path = out / filename
        header = _build_ansi_header(
            version, extra=f"# Font: {font_name} (#{num:03d})\n"
        )
        content = header + "\n".join(lines) + "\n"
        with open(file_path, "w", encoding="utf-8") as fh:
            fh.write(content)


def write_shell_export(
    lines: list[str],
    path: str,
    version: str,
    function_name: str = "show_banner",
) -> None:
    """Write a self-contained bash function that replays the banner.

    The ANSI output is base64-encoded and embedded inline.
    Raises ValueError if function_name is not a valid bash identifier.
    Raises OSError on write failure.
    """
    if not _VALID_FUNCTION_NAME.match(function_name):
        raise ValueError(
            f"invalid function name '{function_name}': "
            "must be a valid bash identifier (letters, digits, underscores; "
            "cannot start with a digit)"
        )
    ansi_bytes = ("\n".join(lines) + "\n").encode("utf-8")
    b64 = base64.b64encode(ansi_bytes).decode("ascii")
    script = (
        f"#!/usr/bin/env bash\n"
        f"# Generated by color-banner {version}\n"
        f"# {_ATTRIBUTION_LINE1}\n"
        f"# {_ATTRIBUTION_LINE2}\n"
        f"# Requires: base64 (GNU coreutils or macOS; OpenBSD uses b64decode instead)\n"
        f"# Paste this function into your script or .bashrc\n"
        f"{function_name}() {{\n"
        f"  command -v base64 >/dev/null 2>&1 || {{ printf 'color-banner: base64 not found\\n' >&2; return 1; }}\n"
        f"  printf '%s' '{b64}' | base64 -d\n"
        f"}}\n"
        f"{function_name}\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(script)


_ANSI_SPAN_RE = re.compile(r"\x1b\[38;2;(\d+);(\d+);(\d+)m([^\x1b]*)\x1b\[0m")


def _ansi_to_html_spans(lines: list[str]) -> str:
    """Convert ANSI-colored lines to an HTML <pre> block with inline-styled spans."""
    html_lines = []
    for line in lines:
        out = ""
        pos = 0
        for m in _ANSI_SPAN_RE.finditer(line):
            if m.start() > pos:
                out += _html_escape(line[pos:m.start()])
            r, g, b, ch = m.group(1), m.group(2), m.group(3), m.group(4)
            out += f'<span style="color:rgb({r},{g},{b})">{_html_escape(ch)}</span>'
            pos = m.end()
        if pos < len(line):
            out += _html_escape(line[pos:])
        html_lines.append(out)
    return "<pre>" + "\n".join(html_lines) + "</pre>"


def write_html_file(lines: list[str], path: str, version: str) -> None:
    """Write a self-contained HTML page with the colored banner to path.

    Parent directories are created automatically.
    Raises OSError on write failure.
    """
    pre = _ansi_to_html_spans(lines)
    page = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        f"<!-- Generated by color-banner {version} -->\n"
        f"<!-- {_ATTRIBUTION_LINE1} -->\n"
        f"<!-- {_ATTRIBUTION_LINE2} -->\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<style>\n"
        "  body { background: #1a1a1a; margin: 2rem; }\n"
        "  pre { font-family: monospace; font-size: 1rem; line-height: 1.3; }\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        f"{pre}\n"
        "</body>\n"
        "</html>\n"
    )
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(page)


def write_html_snippet(lines: list[str]) -> None:
    """Print an HTML <pre> snippet of the colored banner to stdout."""
    print(_ansi_to_html_spans(lines))
